server:
    port: 8203
spring:
    profiles: test 
    application:
        name: application-test-simple
eureka:
    client:
        service-url:
            defaultZone: http://localhost:8761/eureka