
server:
    port: 8203
spring:
    profiles: dev 
    application:
        name:  application-dev-simple
eureka:
    client:
        service-url:
            defaultZone: http://localhost:8761/eureka

